---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: debian
provisioner:
  name: ansible
  playbooks:
    cleanup: cleanup.yml
verifier:
  name: ansible
